# XOPT - OR-LIBRARY p-MEDIAN WITH MIP

It solves every OR-Library p-median instance with the exact `python-mip` formulation, reporting runtime, solver status, and gap to the published best-known value.

### SETUP

Importing the libraries:

In [1]:
import gc
import os
import sys

import numpy  as np
import pandas as pd

from IPython.display import display
from time            import perf_counter
from mip             import OptimizationStatus

In [2]:
from lib.paths     import find_project_root, instance_sort_key

from lib.instances import (
    list_orlibrary_instances     ,
    apply_instance_selection     ,
    load_best_known_costs_to_dict,
)

from lib.metrics   import gap_to_reference_percent
from lib.graph     import read_orlibrary_graph    , all_pairs_shortest_paths
from lib.mip       import extract_open_facilities , compute_solution_cost   , build_pmedian_model
from lib.utils     import finite_or_none          , normalize_number        , parse_optional_int_env

Find the project root directory:

In [3]:
PROJECT_ROOT = find_project_root()

if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

print(f'PROJECT_ROOT = {PROJECT_ROOT}')

PROJECT_ROOT = /home/rei-luisinho/xopt

### EXPERIMENT CONFIGURATION

In [4]:
INSTANCES_DIR = PROJECT_ROOT  / 'instances'
PMEDOPT_PATH  = INSTANCES_DIR / 'pmedopt.txt'
OUTPUT_DIR    = PROJECT_ROOT  / 'notebooks' / 'experiments_sbpo' / 'artifacts'

EXACT_MIP_OUTPUT_PATH = OUTPUT_DIR / 'mip_exact_results.csv'


TIME_LIMIT_SECONDS = parse_optional_int_env('PMED_TIME_LIMIT_SECONDS') or 180
MAX_INSTANCES      = parse_optional_int_env('PMED_MAX_INSTANCES'     )

INSTANCE_FILTER = os.getenv('PMED_INSTANCE_FILTER')

CANONICAL_INSTANCE_NAMES = [
    f'pmed{i}.txt' for i in range(1, 41)
]

ALL_INSTANCE_NAMES = list_orlibrary_instances(INSTANCES_DIR)
INSTANCE_NAMES     = apply_instance_selection(
    ALL_INSTANCE_NAMES,
    pattern=INSTANCE_FILTER,
    limit  =MAX_INSTANCES  ,
)
BEST_KNOWN_COSTS = load_best_known_costs_to_dict(PMEDOPT_PATH)

if not INSTANCE_NAMES:
    raise FileNotFoundError(
        f'No p-median instances were selected from {INSTANCES_DIR}.'
    )

In [5]:
print(f'Instances directory  : {INSTANCES_DIR}')
print(f'Instances discovered : {len(ALL_INSTANCE_NAMES)}')
print(f'Instances selected   : {len(INSTANCE_NAMES    )}')

Instances directory  : /home/rei-luisinho/xopt/instances
Instances discovered : 40
Instances selected   : 40

In [6]:
print(f'Time limit per instance (s) : {TIME_LIMIT_SECONDS}')

Time limit per instance (s) : 180

In [7]:
missing_canonical = sorted(set(CANONICAL_INSTANCE_NAMES) - set(ALL_INSTANCE_NAMES      ), key=instance_sort_key)
extra_instances   = sorted(set(ALL_INSTANCE_NAMES      ) - set(CANONICAL_INSTANCE_NAMES), key=instance_sort_key)
missing_optima    = sorted(set(ALL_INSTANCE_NAMES      ) - set(BEST_KNOWN_COSTS        ), key=instance_sort_key)

if missing_canonical:
    print(f'Missing canonical OR-Library instances: {missing_canonical}')
else:
    print('All 40 canonical OR-Library instances are present.')

if extra_instances:
    print(f'Additional instances discovered    : {extra_instances}')

if missing_optima:
    print(f'Instances without best-known value : {missing_optima}')

print()
print('Instances to solve:')
print(', '.join(name.removesuffix('.txt') for name in INSTANCE_NAMES))

All 40 canonical OR-Library instances are present.

Instances to solve:
pmed1, pmed2, pmed3, pmed4, pmed5, pmed6, pmed7, pmed8, pmed9, pmed10, pmed11, pmed12, pmed13, pmed14, pmed15, pmed16, pmed17, pmed18, pmed19, pmed20, pmed21, pmed22, pmed23, pmed24, pmed25, pmed26, pmed27, pmed28, pmed29, pmed30, pmed31, pmed32, pmed33, pmed34, pmed35, pmed36, pmed37, pmed38, pmed39, pmed40

### EXACT MIP

In [8]:
def solve_instance_with_exact_mip(
    instance_name      : str,
    time_limit_seconds : int = TIME_LIMIT_SECONDS,
) -> dict[str, object]:
    instance_path = INSTANCES_DIR / instance_name

    graph            = read_orlibrary_graph(instance_path)
    best_known_value = finite_or_none      (BEST_KNOWN_COSTS.get(instance_name))

    preprocess_start   = perf_counter()
    distances          = all_pairs_shortest_paths(graph['adjacency'])
    preprocess_seconds = perf_counter() - preprocess_start

    build_start   = perf_counter()
    model, x, y   = build_pmedian_model(distances, graph['p'])
    build_seconds = perf_counter() - build_start

    solve_start   = perf_counter()
    status        = model.optimize(max_seconds=time_limit_seconds)
    solve_seconds = perf_counter() - solve_start

    has_incumbent = status in {
        OptimizationStatus.OPTIMAL ,
        OptimizationStatus.FEASIBLE,
    }

    solver_objective_value = finite_or_none(
        model.objective_value if has_incumbent else None
    )

    open_facilities_zero_based: list[int] = []
    validated_objective_value             = None

    if has_incumbent:
        open_facilities_zero_based = extract_open_facilities(y)

        if len(open_facilities_zero_based) != graph['p']:
            raise ValueError(
                f'Expected {graph["p"]} open facilities, but recovered '
                f'{len(open_facilities_zero_based)}.'
            )

        validated_objective_value = compute_solution_cost(
            distances, open_facilities_zero_based
        )

        if solver_objective_value    is not None and \
           validated_objective_value is not None and \
           abs(solver_objective_value - validated_objective_value) > 1e-4:
            raise ValueError(
                 'Solver objective and validated objective do not match: '
                f'{solver_objective_value} vs {validated_objective_value}.'
            )

        if validated_objective_value is not None and \
           best_known_value          is not None and \
           validated_objective_value + 1e-6 < best_known_value:
            raise ValueError(
                 'Validated objective is below the published best-known '
                f'value: {validated_objective_value} < {best_known_value}.'
            )

    objective_value = (
        validated_objective_value
        if   validated_objective_value is not None
        else solver_objective_value
    )

    open_facilities = [
        facility + 1
        for facility in open_facilities_zero_based
    ]

    result = {
        'instance'         : instance_name,
        'n'                : graph['n'],
        'm'                : graph['m'],
        'p'                : graph['p'],
        'best_known_value' : normalize_number(best_known_value),

        'objective_value'           : normalize_number(objective_value),
        'gap_to_best_known_percent' : normalize_number(
            gap_to_reference_percent(objective_value, best_known_value)
        ),

        'matches_best_known': (
            objective_value  is not None and
            best_known_value is not None and
            abs(objective_value - best_known_value) < 1e-6
        ),

        'preprocess_seconds'  : normalize_number(preprocess_seconds           ),
        'model_build_seconds' : normalize_number(build_seconds                ),
        'solve_seconds'       : normalize_number(solve_seconds                ),
        'mip_stage_seconds'   : normalize_number(build_seconds + solve_seconds),
        'total_seconds'       : normalize_number(
            preprocess_seconds + build_seconds + solve_seconds
        ),

        'open_facilities_count' : len     (         open_facilities ),
        'open_facilities'       : ' '.join(map(str, open_facilities)),

        'status' : getattr(status, 'name', str(status)),
        'error'  : '',
    }

    del model
    del x
    del y
    del distances

    gc.collect()

    return result


def attempt_solve_instance_with_exact_mip(
    instance_name      : str,
    time_limit_seconds : int = TIME_LIMIT_SECONDS,
) -> dict[str, object]:
    try:
        return solve_instance_with_exact_mip(
            instance_name,
            time_limit_seconds=time_limit_seconds,
        )
    except Exception as exc:
        gc.collect()

        return {
            'instance'         : instance_name,
            'n'                : None         ,
            'm'                : None         ,
            'p'                : None         ,
            'best_known_value' : normalize_number(
                BEST_KNOWN_COSTS.get(instance_name)
            ),

            'objective_value'           : None ,
            'gap_to_best_known_percent' : None ,
            'matches_best_known'        : False,

            'preprocess_seconds'  : None,
            'model_build_seconds' : None,
            'solve_seconds'       : None,
            'mip_stage_seconds'   : None,
            'total_seconds'       : None,

            'open_facilities_count' : 0 ,
            'open_facilities'       : '',

            'status' : 'ERROR' ,
            'error'  : str(exc),
        }

### APPLY

In [9]:
RESULTS = []

for index, instance_name in enumerate(INSTANCE_NAMES, start=1):
    print(f'[{index:02d}/{len(INSTANCE_NAMES):02d}] Solving {instance_name}...')

    result = attempt_solve_instance_with_exact_mip(
        instance_name,
        time_limit_seconds=TIME_LIMIT_SECONDS,
    )

    RESULTS.append(result)

    print(
        f"  mip_status={  result['status'                   ]},"
        f" mip_obj={      result['objective_value'          ]},"
        f" mip_gap={      result['gap_to_best_known_percent']},"
        f" total_seconds={result['total_seconds'            ]}"
    )

    if result['error']:
        print(f"  error={result['error']}")

RESULTS_DF = pd.DataFrame(RESULTS)

[01/40] Solving pmed1.txt...
  mip_status=OPTIMAL, mip_obj=5819, mip_gap=0, total_seconds=1.3159
[02/40] Solving pmed2.txt...
  mip_status=OPTIMAL, mip_obj=4093, mip_gap=0, total_seconds=1.9544
[03/40] Solving pmed3.txt...
  mip_status=OPTIMAL, mip_obj=4250, mip_gap=0, total_seconds=1.9667
[04/40] Solving pmed4.txt...
  mip_status=OPTIMAL, mip_obj=3034, mip_gap=0, total_seconds=1.1429
[05/40] Solving pmed5.txt...
  mip_status=OPTIMAL, mip_obj=1355, mip_gap=0, total_seconds=1.1798
[06/40] Solving pmed6.txt...
  mip_status=OPTIMAL, mip_obj=7824, mip_gap=0, total_seconds=157.9406
[07/40] Solving pmed7.txt...
  mip_status=OPTIMAL, mip_obj=5631, mip_gap=0, total_seconds=9.2859
[08/40] Solving pmed8.txt...
  mip_status=OPTIMAL, mip_obj=4445, mip_gap=0, total_seconds=9.5144
[09/40] Solving pmed9.txt...
  mip_status=OPTIMAL, mip_obj=2734, mip_gap=0, total_seconds=9.1776
[10/40] Solving pmed10.txt...
  mip_status=OPTIMAL, mip_obj=1255, mip_gap=0, total_seconds=9.4076
[11/40] Solving pmed11.txt...
  mip_status=OPTIMAL, mip_obj=7696, mip_gap=0, total_seconds=111.5391
[12/40] Solving pmed12.txt...
  mip_status=OPTIMAL, mip_obj=6634, mip_gap=0, total_seconds=49.5154
[13/40] Solving pmed13.txt...
  mip_status=OPTIMAL, mip_obj=4374, mip_gap=0, total_seconds=7.5524
[14/40] Solving pmed14.txt...
  mip_status=OPTIMAL, mip_obj=2968, mip_gap=0, total_seconds=10.5538
[15/40] Solving pmed15.txt...
  mip_status=OPTIMAL, mip_obj=1729, mip_gap=0, total_seconds=7.8664
[16/40] Solving pmed16.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=186.2633
[17/40] Solving pmed17.txt...
  mip_status=FEASIBLE, mip_obj=7009, mip_gap=0.1429, total_seconds=184.0889
[18/40] Solving pmed18.txt...
  mip_status=OPTIMAL, mip_obj=4809, mip_gap=0, total_seconds=23.6374
[19/40] Solving pmed19.txt...
  mip_status=OPTIMAL, mip_obj=2845, mip_gap=0, total_seconds=18.8668
[20/40] Solving pmed20.txt...
  mip_status=OPTIMAL, mip_obj=1789, mip_gap=0, total_seconds=21.2794
[21/40] Solving pmed21.txt...
  mip_status=OPTIMAL, mip_obj=9138, mip_gap=0, total_seconds=39.4659
[22/40] Solving pmed22.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=191.696
[23/40] Solving pmed23.txt...
  mip_status=OPTIMAL, mip_obj=4619, mip_gap=0, total_seconds=36.0825
[24/40] Solving pmed24.txt...
  mip_status=OPTIMAL, mip_obj=2961, mip_gap=0, total_seconds=38.4203
[25/40] Solving pmed25.txt...
  mip_status=OPTIMAL, mip_obj=1828, mip_gap=0, total_seconds=39.0362
[26/40] Solving pmed26.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=203.5704
[27/40] Solving pmed27.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=204.2923
[28/40] Solving pmed28.txt...
  mip_status=OPTIMAL, mip_obj=4498, mip_gap=0, total_seconds=69.6742
[29/40] Solving pmed29.txt...
  mip_status=OPTIMAL, mip_obj=3033, mip_gap=0, total_seconds=62.3444
[30/40] Solving pmed30.txt...
  mip_status=OPTIMAL, mip_obj=1989, mip_gap=0, total_seconds=63.2245
[31/40] Solving pmed31.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=229.7554
[32/40] Solving pmed32.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=223.3657
[33/40] Solving pmed33.txt...
  mip_status=OPTIMAL, mip_obj=4700, mip_gap=0, total_seconds=92.0085
[34/40] Solving pmed34.txt...
  mip_status=OPTIMAL, mip_obj=3013, mip_gap=0, total_seconds=96.4063
[35/40] Solving pmed35.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=242.2275
[36/40] Solving pmed36.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=235.5594
[37/40] Solving pmed37.txt...
  mip_status=OPTIMAL, mip_obj=5057, mip_gap=0, total_seconds=171.7371
[38/40] Solving pmed38.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=260.2758
[39/40] Solving pmed39.txt...
  mip_status=NO_SOLUTION_FOUND, mip_obj=None, mip_gap=None, total_seconds=253.3202
[40/40] Solving pmed40.txt...
  mip_status=OPTIMAL, mip_obj=5128, mip_gap=0, total_seconds=195.0381

Saving the results:

In [10]:
OUTPUT_DIR.mkdir (parents=True         , exist_ok=True )
RESULTS_DF.to_csv(EXACT_MIP_OUTPUT_PATH, index   =False)

print(f'Exact MIP results saved to: {EXACT_MIP_OUTPUT_PATH}')

Exact MIP results saved to: /home/rei-luisinho/xopt/notebooks/experiments_sbpo/artifacts/mip_exact_results.csv

Displaying the results:

In [11]:
def print_table_summary(
    dataframe     : pd.DataFrame,
    label         : str,
    objective_col : str,
    gap_col       : str,
    time_col      : str,
) -> None:
    solved_count  = int(dataframe[objective_col].notna().sum())
    matches_count = int(
        (dataframe[gap_col].fillna(np.inf).abs() < 1e-6).sum()
    )

    mean_time = dataframe[time_col].dropna().mean()
    mean_gap  = dataframe[gap_col ].dropna().mean()

    print(label)
    print(f'  solved instances            : {solved_count }/{len(dataframe)}')
    print(f'  matches best-known          : {matches_count}/{len(dataframe)}')
    print(f'  mean time (s)               : {normalize_number(mean_time)}')
    print(f'  mean gap to best-known (%)  : {normalize_number(mean_gap )}')
    print()


print_table_summary(
    RESULTS_DF,
    label        ='Exact MIP summary:',
    objective_col='objective_value'   ,
    gap_col ='gap_to_best_known_percent',
    time_col='total_seconds'            ,
)

Exact MIP summary:
  solved instances            : 30/40
  matches best-known          : 29/40
  mean time (s)               : 94.2887
  mean gap to best-known (%)  : 0.0048

Approach overview:

In [12]:
EXACT_MIP_DISPLAY_DF = RESULTS_DF[
    [
        'instance'                 ,
        'best_known_value'         ,
        'objective_value'          ,
        'gap_to_best_known_percent',

        'solve_seconds',
        'total_seconds',
        'status'       ,
    ]
].copy()

In [13]:
APPROACH_SUMMARY_DF = pd.DataFrame(
    [
        {
            'approach'  : 'Exact MIP'    ,
            'instances' : len(RESULTS_DF),

            'mean_runtime_seconds'           : normalize_number(RESULTS_DF['total_seconds'            ].dropna().mean()),
            'mean_gap_to_best_known_percent' : normalize_number(RESULTS_DF['gap_to_best_known_percent'].dropna().mean()),
        }
    ]
)

display(APPROACH_SUMMARY_DF)

    approach  instances  mean_runtime_seconds  mean_gap_to_best_known_percent
0  Exact MIP         40               94.2887                          0.0048

Exact MIP per-instance results:

In [14]:
display(EXACT_MIP_DISPLAY_DF)

,instance,best_known_value,objective_value,gap_to_best_known_percent,solve_seconds,total_seconds,status
0,pmed1.txt,5819,5819.0,0.0000,1.1433,1.3159,OPTIMAL
1,pmed2.txt,4093,4093.0,0.0000,1.8536,1.9544,OPTIMAL
2,pmed3.txt,4250,4250.0,0.0000,1.8650,1.9667,OPTIMAL
3,pmed4.txt,3034,3034.0,0.0000,1.0306,1.1429,OPTIMAL
4,pmed5.txt,1355,1355.0,0.0000,1.0880,1.1798,OPTIMAL
5,pmed6.txt,7824,7824.0,0.0000,157.4519,157.9406,OPTIMAL
6,pmed7.txt,5631,5631.0,0.0000,8.9024,9.2859,OPTIMAL
7,pmed8.txt,4445,4445.0,0.0000,9.1346,9.5144,OPTIMAL
8,pmed9.txt,2734,2734.0,0.0000,8.8001,9.1776,OPTIMAL
9,pmed10.txt,1255,1255.0,0.0000,9.0433,9.4076,OPTIMAL
10,pmed11.txt,7696,7696.0,0.0000,110.5773,111.5391,OPTIMAL
11,pmed12.txt,6634,6634.0,0.0000,48.5286,49.5154,OPTIMAL
12,pmed13.txt,4374,4374.0,0.0000,6.5915,7.5524,OPTIMAL
13,pmed14.txt,2968,2968.0,0.0000,9.6159,10.5538,OPTIMAL
14,pmed15.txt,1729,1729.0,0.0000,6.9432,7.8664,OPTIMAL
15,pmed16.txt,8162,NaN,NaN,184.4323,186.2633,NO_SOLUTION_FOUND
16,pmed17.txt,6999,7009.0,0.1429,182.2113,184.0889,FEASIBLE
17,pmed18.txt,4809,4809.0,0.0000,21.8232,23.6374,OPTIMAL
18,pmed19.txt,2845,2845.0,0.0000,17.0519,18.8668,OPTIMAL
19,pmed20.txt,1789,1789.0,0.0000,19.4803,21.2794,OPTIMAL
20,pmed21.txt,9138,9138.0,0.0000,36.4862,39.4659,OPTIMAL
21,pmed22.txt,8579,NaN,NaN,188.6617,191.6960,NO_SOLUTION_FOUND
22,pmed23.txt,4619,4619.0,0.0000,33.0833,36.0825,OPTIMAL
23,pmed24.txt,2961,2961.0,0.0000,35.3722,38.4203,OPTIMAL
24,pmed25.txt,1828,1828.0,0.0000,36.0237,39.0362,OPTIMAL
25,pmed26.txt,9917,NaN,NaN,198.9022,203.5704,NO_SOLUTION_FOUND
26,pmed27.txt,8307,NaN,NaN,199.6385,204.2923,NO_SOLUTION_FOUND
27,pmed28.txt,4498,4498.0,0.0000,64.9786,69.6742,OPTIMAL
28,pmed29.txt,3033,3033.0,0.0000,57.6527,62.3444,OPTIMAL
29,pmed30.txt,1989,1989.0,0.0000,58.5988,63.2245,OPTIMAL
30,pmed31.txt,10086,NaN,NaN,223.2119,229.7554,NO_SOLUTION_FOUND
31,pmed32.txt,9297,NaN,NaN,216.7646,223.3657,NO_SOLUTION_FOUND
32,pmed33.txt,4700,4700.0,0.0000,85.4365,92.0085,OPTIMAL
33,pmed34.txt,3013,3013.0,0.0000,90.0371,96.4063,OPTIMAL
34,pmed35.txt,10400,NaN,NaN,233.5603,242.2275,NO_SOLUTION_FOUND
35,pmed36.txt,9934,NaN,NaN,226.4963,235.5594,NO_SOLUTION_FOUND
36,pmed37.txt,5057,5057.0,0.0000,162.3789,171.7371,OPTIMAL
37,pmed38.txt,11060,NaN,NaN,248.3983,260.2758,NO_SOLUTION_FOUND
38,pmed39.txt,9423,NaN,NaN,241.6168,253.3202,NO_SOLUTION_FOUND
39,pmed40.txt,5128,5128.0,0.0000,183.3039,195.0381,OPTIMAL